//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perfume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public int id { get; set; }
        public int idHoaDon { get; set; }
        public int idsanPham { get; set; }
        public int soLuong { get; set; }
        public Nullable<int> giamGia { get; set; }
        public Nullable<int> thanhTien { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual sanPham sanPham { get; set; }
    }
}
