//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perfume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public int idGioHang { get; set; }
        public int idSanPham { get; set; }
        public string tenSanPham { get; set; }
        public Nullable<int> soLuong { get; set; }
        public Nullable<double> tongTien { get; set; }
    
        public virtual sanPham sanPham { get; set; }
    }
}
