//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perfume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sanPham()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
            this.GioHangs = new HashSet<GioHang>();
        }
    
        public int id { get; set; }
        public string tenSanPham { get; set; }
        public string hinhAnh { get; set; }
        public int idThuongHieu { get; set; }
        public int idLoai { get; set; }
        public double gia { get; set; }
        public Nullable<bool> tinhTrang { get; set; }
        public Nullable<int> hanSuDung { get; set; }
        public Nullable<double> dungTich { get; set; }
        public Nullable<int> soLuong { get; set; }
        public string moTa { get; set; }
        public Nullable<bool> Yeuthich { get; set; }
        public Nullable<int> SoSao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHangs { get; set; }
        public virtual Loai Loai { get; set; }
        public virtual thuongHieu thuongHieu { get; set; }
    }
}
